name: Send Trial Emails Cron

on:
  schedule:
    # Tous les jours à 8h UTC (à adapter si tu veux)
    - cron: "0 8 * * *"
  workflow_dispatch: # Pour lancer manuellement depuis GitHub

jobs:
  send-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Debug working directory and files
        run: |
          pwd
          ls -l ./script/

      - name: Run trial email script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: pnpm exec ts-node -r tsconfig-paths/register ./script/send-trial-emails.ts
